### ISSUE TITLE
cpExternal has an error: 'int java.lang.String.lastIndexOf(int)' on a null object reference

### ISSUE THREAD

**Issue by dazzyjong** [alpha0010/react-native-file-access#20]
Environment: pre android Q (API 29) ONLY.

    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
        at android.os.Parcel.createException(Parcel.java:1972)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
        at android.content.ContentResolver.insert(ContentResolver.java:1594)
        at com.alpha0010.fs.FileAccessModule.cpExternal(FileAccessModule.kt:132)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)

**Comment by alpha0010** [comment]
Do you have a code snippet of what you are running?

Is it every/most API < 29, or a specific one?

**Comment by alpha0010** [comment]
Looks like it might be https://stackoverflow.com/questions/40480156/error-when-executing-contentresolver-insert .  I will try the fix.
